/**
 * Seed Script: Vritilife Facial Toner Product
 * 
 * Run with: node prisma/seedVritilife.js
 */

const { PrismaClient } = require("@prisma/client");
const crypto = require("crypto");

const prisma = new PrismaClient();

async function main() {
    console.log("🌿 Seeding Vritilife Facial Toner...\n");

    // 1. Create the Herbs (ingredients)
    console.log("📦 Creating herbs/ingredients...");

    const aloeVera = await prisma.herb.upsert({
        where: { id: 1 },
        update: {},
        create: {
            commonName: "Aloe Vera",
            scientificName: "Aloe barbadensis",
            specialty: "Soothing & hydrating properties. Used in Ayurveda as Kanyasara for skin care and healing.",
            region: "India, Africa, Caribbean",
            imageUrl: null,
        },
    });
    console.log(`  ✅ Created: ${aloeVera.commonName}`);

    const cucumber = await prisma.herb.upsert({
        where: { id: 2 },
        update: {},
        create: {
            commonName: "Cucumber",
            scientificName: "Cucumis sativus",
            specialty: "Cooling & refreshing. Known as Tanspusam in Ayurveda. Rich in antioxidants.",
            region: "India, Mediterranean",
            imageUrl: null,
        },
    });
    console.log(`  ✅ Created: ${cucumber.commonName}`);

    const potashAlum = await prisma.herb.upsert({
        where: { id: 3 },
        update: {},
        create: {
            commonName: "Potash Alum",
            scientificName: "Potassium Aluminum Sulfate",
            specialty: "Natural astringent mineral. Known as Sphatika in Ayurveda. Tightens pores and purifies.",
            region: "Mineral source",
            imageUrl: null,
        },
    });
    console.log(`  ✅ Created: ${potashAlum.commonName}`);

    // Create the main product herb entry (composite)
    const facialToner = await prisma.herb.upsert({
        where: { id: 4 },
        update: {},
        create: {
            commonName: "Facial Toner – Vritilife",
            scientificName: "Multi-ingredient Ayurvedic Formula",
            specialty: "Contains: Aloe Vera (Kanyasara), Cucumber (Tanspusam), Potash Alum (Sphatika), Phenoxyethanol (preservative), and natural excipients. Balances skin pH and tightens pores.",
            region: "Made in India",
            imageUrl: null,
        },
    });
    console.log(`  ✅ Created: ${facialToner.commonName}`);

    // 2. Create a Farmer/Manufacturer
    console.log("\n🧑‍🌾 Creating manufacturer...");

    const manufacturer = await prisma.farmer.upsert({
        where: { id: 1 },
        update: {},
        create: {
            name: "Vritilife Ayurvedics Pvt. Ltd.",
            mobile: "+91-9876543210",
            location: "Pune, Maharashtra, India",
        },
    });
    console.log(`  ✅ Created: ${manufacturer.name}`);

    // 3. Create a Processor
    console.log("\n⚙️ Creating processor...");

    const processor = await prisma.processor.upsert({
        where: { id: 1 },
        update: {},
        create: {
            name: "Vritilife Manufacturing Unit",
            licenseNo: "AYU-MH-2024-001",
            location: "Pune, Maharashtra",
        },
    });
    console.log(`  ✅ Created: ${processor.name}`);

    // 4. Create a Lab
    console.log("\n🔬 Creating lab...");

    const lab = await prisma.lab.upsert({
        where: { id: 1 },
        update: {},
        create: {
            name: "NABL Certified Testing Lab",
            accreditationNo: "NABL-TC-2024-0567",
            location: "Mumbai, Maharashtra",
        },
    });
    console.log(`  ✅ Created: ${lab.name}`);

    // 5. Create the Batch
    console.log("\n📦 Creating batch: VRITI-TONER-001...");

    const batchId = "VRITI-TONER-001";

    // Generate blockchain transaction ID (simulated)
    const txId = crypto.createHash("sha256")
        .update(JSON.stringify({ batchId, timestamp: new Date().toISOString() }))
        .digest("hex");

    const batch = await prisma.herbBatch.upsert({
        where: { id: batchId },
        update: {},
        create: {
            id: batchId,
            herbId: facialToner.id,
            farmerId: manufacturer.id,
            geoLocation: "18.5204° N, 73.8567° E",
            harvestDate: new Date("2026-01-15"),
            quantity: "500 units (100ml each)",
            status: "LAB_TESTED",
            blockchainTxId: txId,
            qrCodeUrl: null, // Will be generated by API
        },
    });
    console.log(`  ✅ Created batch: ${batch.id}`);

    // 6. Add Processing Record
    console.log("\n⚙️ Adding processing record...");

    const processingTxId = crypto.createHash("sha256")
        .update(JSON.stringify({ batchId, type: "processing", timestamp: new Date().toISOString() }))
        .digest("hex");

    await prisma.processingRecord.create({
        data: {
            batchId: batchId,
            processorId: processor.id,
            method: "Cold-pressed extraction, pH balancing, sterile bottling",
            processDate: new Date("2026-01-20"),
            blockchainTxId: processingTxId,
        },
    });
    console.log(`  ✅ Added processing record`);

    // 7. Add Lab Report
    console.log("\n🧪 Adding lab report...");

    const labTxId = crypto.createHash("sha256")
        .update(JSON.stringify({ batchId, type: "lab", timestamp: new Date().toISOString() }))
        .digest("hex");

    await prisma.labReport.create({
        data: {
            batchId: batchId,
            labId: lab.id,
            testDate: new Date("2026-01-25"),
            result: "PASS",
            reportHash: "QmX7bVbZTZV8YLs1E6VpLR8RqAYLjVZ...",
            blockchainTxId: labTxId,
        },
    });
    console.log(`  ✅ Added lab report: PASS`);

    console.log("\n✨ Seeding complete!");
    console.log(`\n📱 Verify this product at: /verify/${batchId}`);
    console.log(`\n🔗 To generate QR code, call: GET /api/qr/${batchId}`);
}

main()
    .catch((e) => {
        console.error("❌ Seeding failed:", e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
