// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgjmuseaawdyafavbwal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnam11c2VhYXdkeWFmYXZid2FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NjEwNTcsImV4cCI6MjA3NDUzNzA1N30.efphmsUr5dvokxW36YPM9QS8b1hJZfPG6MrUNtEjjdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});